---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mikefarah/yq
    tag: 'latest'

inputs:
- name: deploy-source
- name: release

outputs:
- name: manifest  

run:
  path: deploy-source/ci/tasks/parameterize-mf.sh
